module.exports.descriptors = [
    'Electric',
    'Lost',
    'Roaring',
    'Silent',
    'Grizzly',
    'Sky',
    'Monster',
    'Hiatus',
    'Forbidden',
    'Prehistoric',
    'Sea',
    'Diamond',
    'Petrified',
    'High',
    'Octane',
    'Visceral',
    'Void',
    'Domination',
    'Groovy',
    'Wook'
]

module.exports.places = [
    'Lands',
    'World',
    'Carnival',
    'Creek Fest',
    'Shore Fest',
    'Spring',
    'Mule Fest',
    'Ghost Fest',
    'Canyon',
    'Grounds',
    'Experience',
    'Paradox',
    'Illusion Fest',
    'Fest',
    'Backcountry Fest',
    'Mountain Fest',
    'Valley Fest',
    'On the Beach',
    'City Fest',
    'Never Fest',
    'Yesterday World'
]